package hledger

import (
	"fmt"
	"math"
	"sort"
	"strings"
	"time"

	"github.com/thedavidweng/monarchmoney-cli/internal/cache"
)

type Data struct {
	Accounts     []cache.Account
	Transactions []cache.Transaction
	Holdings     []cache.Holding
	Anchor       time.Time
}

const (
	openingAccount  = "equity:monarch:opening"
	clearingAccount = "equity:monarch:transfer-clearing"
	baseCommodity   = "$"
)

const header = "; Generated by monarch hledger backup. DO NOT EDIT.\n; Regenerate with: monarch hledger backup\n"

type generator struct {
	accounts  []cache.Account
	byID      map[string]cache.Account
	txIndex   map[string]int
	txs       []cache.Transaction
	holdings  []cache.Holding
	investMap map[string][]cache.Holding
	names     map[string]string
	order     []string
	pairs     map[string]string
	computed  map[string]int64
	anchor    time.Time
}

type Gap struct {
	Account string
	Cents   int64
}

// BalanceGaps reports non-investment accounts whose cached transaction history
// does not explain their Monarch balance. Each gap becomes an opening-balance
// true-up through equity:monarch:opening in the generated journal, and usually
// means the institution feed does not cover the account's full lifetime.
func BalanceGaps(data *Data) []Gap {
	gaps, _ := prepare(data).balanceGaps()
	return gaps
}

func (g *generator) balanceGaps() (gaps []Gap, total int64) {
	for _, id := range g.order {
		if strings.EqualFold(g.byID[id].TypeGroup, "investment") {
			continue
		}
		d := cents(g.byID[id].CurrentBalance) - g.computed[id]
		if d != 0 {
			gaps = append(gaps, Gap{Account: g.names[id], Cents: d})
			total += d
		}
	}
	return gaps, total
}

func prepare(data *Data) *generator {
	g := &generator{
		byID:      make(map[string]cache.Account),
		txIndex:   make(map[string]int),
		investMap: make(map[string][]cache.Holding),
		names:     make(map[string]string),
		anchor:    data.Anchor,
	}

	g.accounts = append(g.accounts, data.Accounts...)
	sort.Slice(g.accounts, func(i, j int) bool { return g.accounts[i].ID < g.accounts[j].ID })
	for _, a := range g.accounts {
		g.byID[a.ID] = a
	}
	g.deriveNames()

	for i := range data.Transactions {
		t := &data.Transactions[i]
		if t.Pending {
			continue
		}
		acc, ok := g.byID[t.AccountID]
		if !ok || strings.EqualFold(acc.TypeGroup, "investment") {
			continue
		}
		g.txs = append(g.txs, *t)
	}
	sort.SliceStable(g.txs, func(i, j int) bool {
		if !g.txs[i].Date.Equal(g.txs[j].Date) {
			return g.txs[i].Date.Before(g.txs[j].Date)
		}
		return g.txs[i].ID < g.txs[j].ID
	})
	for i := range g.txs {
		g.txIndex[g.txs[i].ID] = i
	}

	for _, h := range data.Holdings {
		if _, ok := g.byID[h.AccountID]; ok {
			g.holdings = append(g.holdings, h)
		}
	}
	sort.Slice(g.holdings, func(i, j int) bool { return g.holdings[i].ID < g.holdings[j].ID })
	for _, h := range g.holdings {
		if strings.EqualFold(g.byID[h.AccountID].TypeGroup, "investment") {
			g.investMap[h.AccountID] = append(g.investMap[h.AccountID], h)
		}
	}
	for id := range g.investMap {
		hs := g.investMap[id]
		sort.Slice(hs, func(i, j int) bool {
			ci, cj := isCashTicker(hs[i].Ticker), isCashTicker(hs[j].Ticker)
			if ci != cj {
				return !ci
			}
			return hs[i].Ticker < hs[j].Ticker
		})
	}

	g.order = make([]string, 0, len(g.accounts))
	for _, a := range g.accounts {
		g.order = append(g.order, a.ID)
	}
	sort.SliceStable(g.order, func(i, j int) bool { return g.names[g.order[i]] < g.names[g.order[j]] })

	g.pairTransfers()
	g.computeBalances()
	return g
}

func Generate(data *Data) string {
	g := prepare(data)

	var b strings.Builder
	b.WriteString(header)
	b.WriteByte('\n')
	if len(g.accounts) == 0 && len(g.txs) == 0 && len(g.holdings) == 0 {
		return b.String()
	}

	g.writeCommodities(&b)
	g.writeAccounts(&b)
	g.writePrices(&b)
	g.writeTransactions(&b)
	g.writeOpenings(&b)
	g.writeTrueUps(&b)
	g.writeClosings(&b)
	return b.String()
}

func (g *generator) computeBalances() {
	g.computed = make(map[string]int64)
	add := func(accountID string, c int64) {
		g.computed[accountID] += c
	}
	for i := range g.txs {
		t := &g.txs[i]
		partnerID, paired := g.pairs[t.ID]
		if paired && t.ID > partnerID {
			continue
		}
		switch {
		case paired:
			add(t.AccountID, cents(t.Amount))
			partner := &g.txs[g.txIndex[partnerID]]
			add(partner.AccountID, cents(partner.Amount))
		case strings.EqualFold(t.CategoryGroupType, "transfer"):
			add(t.AccountID, cents(t.Amount))
		default:
			sum := int64(0)
			for _, sp := range t.Splits {
				sum += cents(sp.Amount)
			}
			if len(t.Splits) == 0 {
				sum = cents(t.Amount)
			}
			add(t.AccountID, sum)
		}
	}
}

func (g *generator) deriveNames() {
	used := make(map[string]bool)
	for _, a := range g.accounts {
		base := accountPrefix(a.TypeGroup) + ":monarch:" + slugify(a.DisplayName)
		name := base
		for n := int64(2); used[name]; n++ {
			name = fmt.Sprintf("%s-%d", base, n)
		}
		used[name] = true
		g.names[a.ID] = name
	}
}

func (g *generator) pairTransfers() {
	g.pairs = make(map[string]string)
	groups := make(map[string][]int)
	for i := range g.txs {
		if strings.EqualFold(g.txs[i].CategoryGroupType, "transfer") {
			key := g.txs[i].Date.Format("2006-01-02")
			groups[key] = append(groups[key], i)
		}
	}
	keys := make([]string, 0, len(groups))
	for k := range groups {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		idx := groups[k]
		for a := 0; a < len(idx); a++ {
			if _, done := g.pairs[g.txs[idx[a]].ID]; done {
				continue
			}
			for b := a + 1; b < len(idx); b++ {
				if _, done := g.pairs[g.txs[idx[b]].ID]; done {
					continue
				}
				left, right := &g.txs[idx[a]], &g.txs[idx[b]]
				if left.AccountID != right.AccountID && cents(left.Amount)+cents(right.Amount) == 0 {
					g.pairs[left.ID] = right.ID
					g.pairs[right.ID] = left.ID
					break
				}
			}
		}
	}
}

func (g *generator) writeCommodities(b *strings.Builder) {
	tickers := make(map[string]bool)
	for _, hs := range g.investMap {
		for _, h := range hs {
			if !isCashTicker(h.Ticker) && h.Quantity != 0 {
				tickers[h.Ticker] = true
			}
		}
	}
	fmt.Fprintf(b, "commodity %s\n", baseCommodity)
	sorted := make([]string, 0, len(tickers))
	for t := range tickers {
		sorted = append(sorted, t)
	}
	sort.Strings(sorted)
	for _, t := range sorted {
		fmt.Fprintf(b, "commodity %s\n", t)
	}
	b.WriteByte('\n')
}

func (g *generator) writeAccounts(b *strings.Builder) {
	for _, id := range g.order {
		acc := g.byID[id]
		fmt.Fprintf(b, "account %s\n    ; monarch-id: %s\n", g.names[id], id)
		if acc.AccountType != "" {
			fmt.Fprintf(b, "    ; monarch-type: %s\n", acc.AccountType)
		}
		var flags []string
		for flag, set := range map[string]bool{"closed": acc.IsClosed, "hidden": acc.IsHidden, "manual": acc.IsManual} {
			if set {
				flags = append(flags, flag)
			}
		}
		sort.Strings(flags)
		if len(flags) > 0 {
			fmt.Fprintf(b, "    ; monarch-flags: %s\n", strings.Join(flags, ","))
		}
	}
	b.WriteByte('\n')
}

func (g *generator) writePrices(b *strings.Builder) {
	if g.anchor.IsZero() {
		return
	}
	type agg struct {
		qty, value float64
	}
	prices := make(map[string]*agg)
	for _, h := range g.holdings {
		if isCashTicker(h.Ticker) || h.Quantity == 0 {
			continue
		}
		p, ok := prices[h.Ticker]
		if !ok {
			p = &agg{}
			prices[h.Ticker] = p
		}
		p.qty += h.Quantity
		p.value += h.Value
	}
	tickers := make([]string, 0, len(prices))
	for t := range prices {
		tickers = append(tickers, t)
	}
	sort.Strings(tickers)
	for _, t := range tickers {
		p := prices[t]
		if p.qty == 0 {
			continue
		}
		fmt.Fprintf(b, "P %s %s %s\n", g.anchor.Format("2006-01-02"), t, baseCommodity+price(p.value/p.qty))
	}
	if len(tickers) > 0 {
		b.WriteByte('\n')
	}
}

func (g *generator) writeTransactions(b *strings.Builder) {
	for i := range g.txs {
		t := &g.txs[i]
		partnerID, paired := g.pairs[t.ID]
		if paired && t.ID > partnerID {
			continue
		}
		fmt.Fprintf(b, "%s %s\n", t.Date.Format("2006-01-02"), title(t))
		var partner *cache.Transaction
		if paired && t.ID <= partnerID {
			partner = &g.txs[g.txIndex[partnerID]]
		}
		g.writeMetadata(b, t, partner)
		switch {
		case paired:
			g.posting(b, g.names[t.AccountID], dollars(cents(t.Amount)))
			g.posting(b, g.names[partner.AccountID], dollars(cents(partner.Amount)))
		case strings.EqualFold(t.CategoryGroupType, "transfer"):
			c := cents(t.Amount)
			g.posting(b, g.names[t.AccountID], dollars(c))
			g.posting(b, clearingAccount, dollars(-c))
		default:
			g.categoryPostings(b, t)
		}
		b.WriteByte('\n')
	}
}

func (g *generator) writeMetadata(b *strings.Builder, t, partner *cache.Transaction) {
	fmt.Fprintf(b, "    ; monarch-id: %s\n", t.ID)
	if partnerID := g.pairs[t.ID]; partnerID != "" && t.ID < partnerID {
		fmt.Fprintf(b, "    ; transfer-partner: %s\n", partnerID)
	}
	if note := oneline(t.Notes); note != "" {
		fmt.Fprintf(b, "    ; note: %s\n", note)
	}
	head := title(t)
	if name := oneline(t.PlaidName); name != "" && !strings.EqualFold(name, head) {
		fmt.Fprintf(b, "    ; plaid-name: %s\n", name)
	}
	if name := oneline(t.ProviderDescription); name != "" && !strings.EqualFold(name, head) {
		fmt.Fprintf(b, "    ; provider-description: %s\n", name)
	}
	names := tagNames(t.Tags, nil)
	sort.Strings(names)
	for _, name := range names {
		fmt.Fprintf(b, "    ; tag: %s\n", name)
	}
	if t.GoalName != "" || t.GoalID != "" {
		fmt.Fprintf(b, "    ; goal: %s\n", strings.TrimSpace(oneline(t.GoalName)+" "+t.GoalID))
	}
	if t.ReviewStatus != "" && !strings.EqualFold(t.ReviewStatus, "reviewed") {
		fmt.Fprintf(b, "    ; review-status: %s\n", oneline(t.ReviewStatus))
	}
	if t.HideFromReports {
		fmt.Fprintf(b, "    ; hide-from-reports:\n")
	}
	if t.IsRecurring {
		fmt.Fprintf(b, "    ; recurring:\n")
	}
	if partner == nil {
		return
	}
	headPartner := title(partner)
	if note := oneline(partner.Notes); note != "" && note != oneline(t.Notes) {
		fmt.Fprintf(b, "    ; partner-note: %s\n", note)
	}
	if name := oneline(partner.PlaidName); name != "" && !strings.EqualFold(name, head) && !strings.EqualFold(name, headPartner) {
		fmt.Fprintf(b, "    ; partner-plaid-name: %s\n", name)
	}
	if name := oneline(partner.ProviderDescription); name != "" && !strings.EqualFold(name, head) && !strings.EqualFold(name, headPartner) {
		fmt.Fprintf(b, "    ; partner-provider-description: %s\n", name)
	}
	for _, name := range tagNames(partner.Tags, t.Tags) {
		fmt.Fprintf(b, "    ; tag: %s\n", name)
	}
	if partner.GoalName != "" || partner.GoalID != "" {
		goal := strings.TrimSpace(oneline(partner.GoalName) + " " + partner.GoalID)
		if goal != strings.TrimSpace(oneline(t.GoalName)+" "+t.GoalID) {
			fmt.Fprintf(b, "    ; partner-goal: %s\n", goal)
		}
	}
}

func tagNames(tags, exclude []cache.Tag) []string {
	drop := make(map[string]bool, len(exclude))
	for _, tag := range exclude {
		drop[tag.Name] = true
	}
	names := make([]string, 0, len(tags))
	for _, tag := range tags {
		if !drop[tag.Name] {
			names = append(names, tag.Name)
		}
	}
	return names
}

func (g *generator) categoryPostings(b *strings.Builder, t *cache.Transaction) {
	groupType := t.CategoryGroupType
	if groupType == "" && t.Amount > 0 {
		groupType = "income"
	}
	sum := int64(0)
	if len(t.Splits) > 0 {
		for _, sp := range t.Splits {
			c := cents(sp.Amount)
			sum += c
			line := fmt.Sprintf("%s  %s", categoryName(sp.Category, groupType), dollars(-c))
			if detail := splitDetail(&sp, t); detail != "" {
				line += "  ; " + detail
			}
			fmt.Fprintf(b, "    %s\n", line)
		}
	} else {
		sum = cents(t.Amount)
		g.posting(b, categoryName(t.Category, groupType), dollars(-sum))
	}
	g.posting(b, g.names[t.AccountID], dollars(sum))
}

func (g *generator) writeOpenings(b *strings.Builder) {
	if g.anchor.IsZero() {
		return
	}
	ids := make([]string, 0, len(g.investMap))
	for id := range g.investMap {
		ids = append(ids, id)
	}
	sort.Slice(ids, func(i, j int) bool { return g.names[ids[i]] < g.names[ids[j]] })
	for _, id := range ids {
		total := int64(0)
		var lines []string
		for _, h := range g.investMap[id] {
			var line string
			switch {
			case isCashTicker(h.Ticker):
				c := cents(h.Value)
				total += c
				line = fmt.Sprintf("%s  %s", g.names[id], dollars(c))
			case h.Quantity != 0:
				c := cents(h.Basis)
				total += c
				line = fmt.Sprintf("%s  %s %s @@ %s", g.names[id], quantity(h.Quantity), h.Ticker, dollars(c))
			default:
				continue
			}
			if h.Name != "" {
				line += "  ; name: " + oneline(h.Name)
			}
			lines = append(lines, line)
		}
		if len(lines) == 0 {
			continue
		}
		fmt.Fprintf(b, "%s opening positions %s\n", g.anchor.Format("2006-01-02"), g.names[id])
		fmt.Fprintf(b, "    ; monarch-id: %s\n", id)
		for _, l := range lines {
			fmt.Fprintf(b, "    %s\n", l)
		}
		g.posting(b, openingAccount, dollars(-total))
		b.WriteByte('\n')
	}
}

func (g *generator) writeTrueUps(b *strings.Builder) {
	if g.anchor.IsZero() {
		return
	}
	gaps, total := g.balanceGaps()
	if len(gaps) == 0 {
		return
	}
	date := g.anchor.Format("2006-01-02")
	if len(g.txs) > 0 {
		date = g.txs[0].Date.AddDate(0, 0, -1).Format("2006-01-02")
	}
	fmt.Fprintf(b, "%s opening balances\n", date)
	for _, gap := range gaps {
		g.posting(b, gap.Account, dollars(gap.Cents))
	}
	if total != 0 {
		g.posting(b, openingAccount, dollars(-total))
	}
	b.WriteByte('\n')
}

func (g *generator) writeClosings(b *strings.Builder) {
	if g.anchor.IsZero() {
		return
	}
	type assertion struct {
		account string
		amount  string
	}
	var asserts []assertion
	for _, id := range g.order {
		a := g.byID[id]
		if strings.EqualFold(a.TypeGroup, "investment") {
			for _, h := range g.investMap[id] {
				if !isCashTicker(h.Ticker) && h.Quantity != 0 {
					asserts = append(asserts, assertion{
						account: g.names[id],
						amount:  fmt.Sprintf("0 %s = %s %s", h.Ticker, quantity(h.Quantity), h.Ticker),
					})
				}
			}
			continue
		}
		asserts = append(asserts, assertion{
			account: g.names[id],
			amount:  fmt.Sprintf("%s = %s", dollars(0), dollars(cents(a.CurrentBalance))),
		})
	}
	if len(asserts) == 0 {
		return
	}
	fmt.Fprintf(b, "%s closing balances\n", g.anchor.Format("2006-01-02"))
	for _, a := range asserts {
		g.posting(b, a.account, a.amount)
	}
	b.WriteByte('\n')
}

func (g *generator) posting(b *strings.Builder, account, amount string) {
	fmt.Fprintf(b, "    %s  %s\n", account, amount)
}

func accountPrefix(group string) string {
	switch strings.ToLower(group) {
	case "liability":
		return "liabilities"
	case "investment":
		return "investments"
	default:
		return "assets"
	}
}

func categoryName(category, groupType string) string {
	root := slugify(category)
	if root == "unnamed" {
		root = "uncategorized"
	}
	if strings.EqualFold(groupType, "income") {
		return "income:" + root
	}
	return "expenses:" + root
}

func oneline(s string) string {
	return strings.Join(strings.Fields(s), " ")
}

func splitDetail(sp *cache.Split, t *cache.Transaction) string {
	var parts []string
	if m := oneline(sp.Merchant); m != "" && !strings.EqualFold(m, title(t)) {
		parts = append(parts, "merchant: "+m)
	}
	if n := oneline(sp.Notes); n != "" && n != oneline(t.Notes) {
		parts = append(parts, "note: "+n)
	}
	return strings.Join(parts, " | ")
}

func slugify(name string) string {
	var b strings.Builder
	prevDash := true
	for _, r := range strings.ToLower(name) {
		alnum := (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9')
		if !alnum {
			prevDash = true
			continue
		}
		if prevDash && b.Len() > 0 {
			b.WriteByte('-')
		}
		b.WriteRune(r)
		prevDash = false
	}
	if b.Len() == 0 {
		return "unnamed"
	}
	return b.String()
}

func title(t *cache.Transaction) string {
	for _, s := range []string{t.Merchant, t.PlaidName, t.ProviderDescription} {
		if s = strings.Join(strings.Fields(s), " "); s != "" {
			return s
		}
	}
	return "unknown"
}

func isCashTicker(ticker string) bool {
	return strings.HasPrefix(strings.ToUpper(ticker), "CUR:")
}

func cents(v float64) int64 {
	return int64(math.Round(v * 100))
}

func money(c int64) string {
	sign := ""
	if c < 0 {
		sign = "-"
		c = -c
	}
	return fmt.Sprintf("%s%d.%02d", sign, c/100, c%100)
}

// FormatCents renders a cent amount as a dollar string.
func FormatCents(c int64) string {
	return dollars(c)
}

func dollars(c int64) string {
	return baseCommodity + money(c)
}

func quantity(q float64) string {
	s := fmt.Sprintf("%.6f", q)
	s = strings.TrimRight(s, "0")
	return strings.TrimSuffix(s, ".")
}

func price(p float64) string {
	s := fmt.Sprintf("%.4f", p)
	s = strings.TrimRight(s, "0")
	return strings.TrimSuffix(s, ".")
}
