package hledger

import (
	"fmt"
	"strings"
	"testing"
	"time"

	"github.com/thedavidweng/monarchmoney-cli/internal/cache"
)

func d(date string) time.Time {
	t, _ := time.Parse("2006-01-02", date)
	return t
}

func TestGenerate(t *testing.T) {
	tests := []struct {
		name string
		data Data
		want string
	}{
		{
			name: "empty cache yields header only",
			data: Data{},
			want: "; Generated by monarch hledger backup. DO NOT EDIT.\n; Regenerate with: monarch hledger backup\n\n",
		},
		{
			name: "expense transaction routes to expenses account with closing assertion",
			data: Data{
				Accounts: []cache.Account{
					{ID: "acc_1", DisplayName: "Checking", TypeGroup: "asset", CurrentBalance: 1234.56},
				},
				Transactions: []cache.Transaction{
					{ID: "tx_1", Date: d("2026-05-09"), Amount: -12.34, Merchant: "Coffee", Category: "Dining", CategoryGroupType: "expense", AccountID: "acc_1"},
				},
				Anchor: d("2026-05-10"),
			},
			want: `; Generated by monarch hledger backup. DO NOT EDIT.
; Regenerate with: monarch hledger backup

commodity $

account assets:monarch:checking
    ; monarch-id: acc_1

2026-05-09 Coffee
    ; monarch-id: tx_1
    expenses:dining  $12.34
    assets:monarch:checking  $-12.34

2026-05-08 opening balances
    assets:monarch:checking  $1246.90
    equity:monarch:opening  $-1246.90

2026-05-10 closing balances
    assets:monarch:checking  $0.00 = $1234.56

`,
		},
		{
			name: "income group routes to income account",
			data: Data{
				Accounts: []cache.Account{
					{ID: "acc_1", DisplayName: "Checking", TypeGroup: "asset", CurrentBalance: 100},
				},
				Transactions: []cache.Transaction{
					{ID: "tx_1", Date: d("2026-05-01"), Amount: 100, Merchant: "Employer Inc", Category: "Paycheck", CategoryGroupType: "income", AccountID: "acc_1"},
				},
				Anchor: d("2026-05-02"),
			},
			want: `; Generated by monarch hledger backup. DO NOT EDIT.
; Regenerate with: monarch hledger backup

commodity $

account assets:monarch:checking
    ; monarch-id: acc_1

2026-05-01 Employer Inc
    ; monarch-id: tx_1
    income:paycheck  $-100.00
    assets:monarch:checking  $100.00

2026-05-02 closing balances
    assets:monarch:checking  $0.00 = $100.00

`,
		},
		{
			name: "paired transfers collapse into one two-posting transaction",
			data: Data{
				Accounts: []cache.Account{
					{ID: "acc_1", DisplayName: "Checking", TypeGroup: "asset"},
					{ID: "acc_2", DisplayName: "Savings", TypeGroup: "asset"},
				},
				Transactions: []cache.Transaction{
					{ID: "tx_a", Date: d("2026-05-01"), Amount: -100, Merchant: "To Savings", Category: "Transfer", CategoryGroupType: "transfer", AccountID: "acc_1"},
					{ID: "tx_b", Date: d("2026-05-01"), Amount: 100, Merchant: "From Checking", Category: "Transfer", CategoryGroupType: "transfer", AccountID: "acc_2"},
				},
				Anchor: d("2026-05-02"),
			},
			want: `; Generated by monarch hledger backup. DO NOT EDIT.
; Regenerate with: monarch hledger backup

commodity $

account assets:monarch:checking
    ; monarch-id: acc_1
account assets:monarch:savings
    ; monarch-id: acc_2

2026-05-01 To Savings
    ; monarch-id: tx_a
    ; transfer-partner: tx_b
    assets:monarch:checking  $-100.00
    assets:monarch:savings  $100.00

2026-04-30 opening balances
    assets:monarch:checking  $100.00
    assets:monarch:savings  $-100.00

2026-05-02 closing balances
    assets:monarch:checking  $0.00 = $0.00
    assets:monarch:savings  $0.00 = $0.00

`,
		},
		{
			name: "collapsed transfer preserves partner metadata",
			data: Data{
				Accounts: []cache.Account{
					{ID: "acc_1", DisplayName: "Checking", TypeGroup: "asset"},
					{ID: "acc_2", DisplayName: "Savings", TypeGroup: "asset"},
				},
				Transactions: []cache.Transaction{
					{ID: "tx_a", Date: d("2026-05-01"), Amount: -100, Merchant: "To Savings", Category: "Transfer", CategoryGroupType: "transfer", AccountID: "acc_1",
						Tags: []cache.Tag{{ID: "t1", Name: "shared"}}},
					{ID: "tx_b", Date: d("2026-05-01"), Amount: 100, Merchant: "From Checking", Category: "Transfer", CategoryGroupType: "transfer", AccountID: "acc_2",
						Notes: "down payment", PlaidName: "SAVINGS XFER", Tags: []cache.Tag{{ID: "t1", Name: "shared"}, {ID: "t2", Name: "house"}}},
				},
				Anchor: d("2026-05-02"),
			},
			want: `; Generated by monarch hledger backup. DO NOT EDIT.
; Regenerate with: monarch hledger backup

commodity $

account assets:monarch:checking
    ; monarch-id: acc_1
account assets:monarch:savings
    ; monarch-id: acc_2

2026-05-01 To Savings
    ; monarch-id: tx_a
    ; transfer-partner: tx_b
    ; tag: shared
    ; partner-note: down payment
    ; partner-plaid-name: SAVINGS XFER
    ; tag: house
    assets:monarch:checking  $-100.00
    assets:monarch:savings  $100.00

2026-04-30 opening balances
    assets:monarch:checking  $100.00
    assets:monarch:savings  $-100.00

2026-05-02 closing balances
    assets:monarch:checking  $0.00 = $0.00
    assets:monarch:savings  $0.00 = $0.00

`,
		},
		{
			name: "unpaired transfer posts against the transfer clearing account",
			data: Data{
				Accounts: []cache.Account{
					{ID: "acc_1", DisplayName: "Checking", TypeGroup: "asset"},
				},
				Transactions: []cache.Transaction{
					{ID: "tx_c", Date: d("2026-05-02"), Amount: -500, Merchant: "To Brokerage", Category: "Transfer", CategoryGroupType: "transfer", AccountID: "acc_1"},
				},
				Anchor: d("2026-05-03"),
			},
			want: `; Generated by monarch hledger backup. DO NOT EDIT.
; Regenerate with: monarch hledger backup

commodity $

account assets:monarch:checking
    ; monarch-id: acc_1

2026-05-02 To Brokerage
    ; monarch-id: tx_c
    assets:monarch:checking  $-500.00
    equity:monarch:transfer-clearing  $500.00

2026-05-01 opening balances
    assets:monarch:checking  $500.00
    equity:monarch:opening  $-500.00

2026-05-03 closing balances
    assets:monarch:checking  $0.00 = $0.00

`,
		},
		{
			name: "split transactions expand into multiple category postings",
			data: Data{
				Accounts: []cache.Account{
					{ID: "acc_1", DisplayName: "Checking", TypeGroup: "asset"},
				},
				Transactions: []cache.Transaction{
					{ID: "tx_1", Date: d("2026-05-09"), Amount: -12.34, Merchant: "Coffee", Category: "Dining", CategoryGroupType: "expense", AccountID: "acc_1",
						Splits: []cache.Split{
							{ID: "sp_1", Amount: -10, Category: "Dining"},
							{ID: "sp_2", Amount: -2.34, Category: "Groceries"},
						}},
				},
				Anchor: d("2026-05-10"),
			},
			want: `; Generated by monarch hledger backup. DO NOT EDIT.
; Regenerate with: monarch hledger backup

commodity $

account assets:monarch:checking
    ; monarch-id: acc_1

2026-05-09 Coffee
    ; monarch-id: tx_1
    expenses:dining  $10.00
    expenses:groceries  $2.34
    assets:monarch:checking  $-12.34

2026-05-08 opening balances
    assets:monarch:checking  $12.34
    equity:monarch:opening  $-12.34

2026-05-10 closing balances
    assets:monarch:checking  $0.00 = $0.00

`,
		},
		{
			name: "pending transactions are excluded",
			data: Data{
				Accounts: []cache.Account{
					{ID: "acc_1", DisplayName: "Checking", TypeGroup: "asset"},
				},
				Transactions: []cache.Transaction{
					{ID: "tx_p", Date: d("2026-05-09"), Amount: -50, Merchant: "Pending Gas", Category: "Auto", CategoryGroupType: "expense", Pending: true, AccountID: "acc_1"},
				},
				Anchor: d("2026-05-10"),
			},
			want: `; Generated by monarch hledger backup. DO NOT EDIT.
; Regenerate with: monarch hledger backup

commodity $

account assets:monarch:checking
    ; monarch-id: acc_1

2026-05-10 closing balances
    assets:monarch:checking  $0.00 = $0.00

`,
		},
		{
			name: "investment accounts use snapshot mode with opening positions and quantity assertions",
			data: Data{
				Accounts: []cache.Account{
					{ID: "acc_1", DisplayName: "Checking", TypeGroup: "asset", CurrentBalance: 1234.56},
					{ID: "acc_2", DisplayName: "Brokerage", TypeGroup: "investment", CurrentBalance: 9400.75},
				},
				Transactions: []cache.Transaction{
					{ID: "tx_1", Date: d("2026-05-09"), Amount: -12.34, Merchant: "Coffee", Category: "Dining", CategoryGroupType: "expense", AccountID: "acc_1"},
					{ID: "tx_2", Date: d("2026-05-08"), Amount: -1000, Merchant: "Managed Buy", Category: "Transfer", CategoryGroupType: "transfer", AccountID: "acc_2"},
				},
				Holdings: []cache.Holding{
					{ID: "h_cash", Ticker: "CUR:USD", Name: "USD", Quantity: 500, Basis: 500, Value: 500, AccountID: "acc_2"},
					{ID: "h_vti", Ticker: "VTI", Name: "Vanguard Total Stock Market ETF", Quantity: 10.5, Basis: 2500, Value: 3000.5, AccountID: "acc_2"},
				},
				Anchor: d("2026-05-10"),
			},
			want: `; Generated by monarch hledger backup. DO NOT EDIT.
; Regenerate with: monarch hledger backup

commodity $
commodity VTI

account assets:monarch:checking
    ; monarch-id: acc_1
account investments:monarch:brokerage
    ; monarch-id: acc_2

P 2026-05-10 VTI $285.7619

2026-05-09 Coffee
    ; monarch-id: tx_1
    expenses:dining  $12.34
    assets:monarch:checking  $-12.34

2026-05-10 opening positions investments:monarch:brokerage
    ; monarch-id: acc_2
    investments:monarch:brokerage  10.5 VTI @@ $2500.00  ; name: Vanguard Total Stock Market ETF
    investments:monarch:brokerage  $500.00  ; name: USD
    equity:monarch:opening  $-3000.00

2026-05-08 opening balances
    assets:monarch:checking  $1246.90
    equity:monarch:opening  $-1246.90

2026-05-10 closing balances
    assets:monarch:checking  $0.00 = $1234.56
    investments:monarch:brokerage  0 VTI = 10.5 VTI

`,
		},
		{
			name: "hidden and closed accounts are included",
			data: Data{
				Accounts: []cache.Account{
					{ID: "acc_1", DisplayName: "Old Card", TypeGroup: "liability", IsHidden: true, IsClosed: true, CurrentBalance: -45.67},
				},
				Anchor: d("2026-05-10"),
			},
			want: `; Generated by monarch hledger backup. DO NOT EDIT.
; Regenerate with: monarch hledger backup

commodity $

account liabilities:monarch:old-card
    ; monarch-id: acc_1
    ; monarch-flags: closed,hidden

2026-05-10 opening balances
    liabilities:monarch:old-card  $-45.67
    equity:monarch:opening  $45.67

2026-05-10 closing balances
    liabilities:monarch:old-card  $0.00 = $-45.67

`,
		},
		{
			name: "slug collisions get deterministic numeric suffixes",
			data: Data{
				Accounts: []cache.Account{
					{ID: "acc_1", DisplayName: "Savings", TypeGroup: "asset"},
					{ID: "acc_2", DisplayName: "Savings!", TypeGroup: "asset"},
				},
				Anchor: d("2026-05-10"),
			},
			want: `; Generated by monarch hledger backup. DO NOT EDIT.
; Regenerate with: monarch hledger backup

commodity $

account assets:monarch:savings
    ; monarch-id: acc_1
account assets:monarch:savings-2
    ; monarch-id: acc_2

2026-05-10 closing balances
    assets:monarch:savings  $0.00 = $0.00
    assets:monarch:savings-2  $0.00 = $0.00

`,
		},
		{
			name: "uncategorized transactions fall back to routed uncategorized accounts",
			data: Data{
				Accounts: []cache.Account{
					{ID: "acc_1", DisplayName: "Checking", TypeGroup: "asset"},
				},
				Transactions: []cache.Transaction{
					{ID: "tx_1", Date: d("2026-05-01"), Amount: -20, Merchant: "Mystery Charge", AccountID: "acc_1"},
					{ID: "tx_2", Date: d("2026-05-02"), Amount: 15, Merchant: "Mystery Income", AccountID: "acc_1"},
				},
				Anchor: d("2026-05-03"),
			},
			want: `; Generated by monarch hledger backup. DO NOT EDIT.
; Regenerate with: monarch hledger backup

commodity $

account assets:monarch:checking
    ; monarch-id: acc_1

2026-05-01 Mystery Charge
    ; monarch-id: tx_1
    expenses:uncategorized  $20.00
    assets:monarch:checking  $-20.00

2026-05-02 Mystery Income
    ; monarch-id: tx_2
    income:uncategorized  $-15.00
    assets:monarch:checking  $15.00

2026-04-30 opening balances
    assets:monarch:checking  $5.00
    equity:monarch:opening  $-5.00

2026-05-03 closing balances
    assets:monarch:checking  $0.00 = $0.00

`,
		},
		{
			name: "merchant title falls back to raw merchant names",
			data: Data{
				Accounts: []cache.Account{
					{ID: "acc_1", DisplayName: "Checking", TypeGroup: "asset"},
				},
				Transactions: []cache.Transaction{
					{ID: "tx_1", Date: d("2026-05-01"), Amount: -5, PlaidName: "SQ *COFFEE CO", ProviderDescription: "Square Coffee", CategoryGroupType: "expense", AccountID: "acc_1"},
				},
				Anchor: d("2026-05-02"),
			},
			want: `; Generated by monarch hledger backup. DO NOT EDIT.
; Regenerate with: monarch hledger backup

commodity $

account assets:monarch:checking
    ; monarch-id: acc_1

2026-05-01 SQ *COFFEE CO
    ; monarch-id: tx_1
    ; provider-description: Square Coffee
    expenses:uncategorized  $5.00
    assets:monarch:checking  $-5.00

2026-04-30 opening balances
    assets:monarch:checking  $5.00
    equity:monarch:opening  $-5.00

2026-05-02 closing balances
    assets:monarch:checking  $0.00 = $0.00

`,
		},
		{
			name: "transaction metadata is preserved as comment tags",
			data: Data{
				Accounts: []cache.Account{
					{ID: "acc_1", DisplayName: "Checking", TypeGroup: "asset", AccountType: "checking", IsManual: true},
				},
				Transactions: []cache.Transaction{
					{ID: "tx_1", Date: d("2026-05-01"), Amount: -15, Merchant: "Blue Bottle", PlaidName: "BLUE BOTTLE COFFEE LLC",
						ProviderDescription: "Blue Bottle Coffee", Category: "Dining", CategoryGroupType: "expense",
						Notes: "team latte\nrun", Pending: false, HideFromReports: true, IsRecurring: true,
						ReviewStatus: "flagged", NeedsReview: true, GoalID: "goal_9", GoalName: "House fund", AccountID: "acc_1",
						Tags:   []cache.Tag{{ID: "t2", Name: "work"}, {ID: "t1", Name: "reimbursable"}},
						Splits: []cache.Split{{ID: "sp_1", Amount: -10, Category: "Dining", Merchant: "Blue Bottle Espresso", Notes: "extra shot"}, {ID: "sp_2", Amount: -5, Category: "Dining"}},
					},
				},
				Anchor: d("2026-05-02"),
			},
			want: `; Generated by monarch hledger backup. DO NOT EDIT.
; Regenerate with: monarch hledger backup

commodity $

account assets:monarch:checking
    ; monarch-id: acc_1
    ; monarch-type: checking
    ; monarch-flags: manual

2026-05-01 Blue Bottle
    ; monarch-id: tx_1
    ; note: team latte run
    ; plaid-name: BLUE BOTTLE COFFEE LLC
    ; provider-description: Blue Bottle Coffee
    ; tag: reimbursable
    ; tag: work
    ; goal: House fund goal_9
    ; review-status: flagged
    ; hide-from-reports:
    ; recurring:
    expenses:dining  $10.00  ; merchant: Blue Bottle Espresso | note: extra shot
    expenses:dining  $5.00
    assets:monarch:checking  $-15.00

2026-04-30 opening balances
    assets:monarch:checking  $15.00
    equity:monarch:opening  $-15.00

2026-05-02 closing balances
    assets:monarch:checking  $0.00 = $0.00

`,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := Generate(&tt.data)
			if got != tt.want {
				t.Fatalf("Generate() mismatch at %s", firstDiff(got, tt.want))
			}
		})
	}
}

func firstDiff(got, want string) string {
	gl := strings.SplitAfter(got, "\n")
	wl := strings.SplitAfter(want, "\n")
	for i := 0; i < len(gl) || i < len(wl); i++ {
		var g, w string
		if i < len(gl) {
			g = gl[i]
		}
		if i < len(wl) {
			w = wl[i]
		}
		if g != w {
			return fmt.Sprintf("line %d:\n--- got  %q\n--- want %q\n--- full got ---\n%s", i+1, g, w, got)
		}
	}
	return ""
}

func TestGenerateIsDeterministicRegardlessOfInputOrder(t *testing.T) {
	newData := func(reverse bool) *Data {
		accounts := []cache.Account{
			{ID: "acc_1", DisplayName: "Checking", TypeGroup: "asset", CurrentBalance: 88.12},
			{ID: "acc_2", DisplayName: "Brokerage", TypeGroup: "investment"},
			{ID: "acc_3", DisplayName: "Savings", TypeGroup: "asset"},
		}
		transactions := []cache.Transaction{
			{ID: "tx_a", Date: d("2026-05-01"), Amount: -100, Merchant: "To Brokerage", Category: "Transfer", CategoryGroupType: "transfer", AccountID: "acc_1"},
			{ID: "tx_b", Date: d("2026-05-01"), Amount: -7.5, Merchant: "Coffee", Category: "Dining", CategoryGroupType: "expense", AccountID: "acc_1"},
			{ID: "tx_d", Date: d("2026-05-02"), Amount: 50, Merchant: "From Checking", Category: "Transfer", CategoryGroupType: "transfer", AccountID: "acc_3"},
			{ID: "tx_c", Date: d("2026-05-02"), Amount: -50, Merchant: "To Savings", Category: "Transfer", CategoryGroupType: "transfer", AccountID: "acc_1"},
		}
		holdings := []cache.Holding{
			{ID: "h_1", Ticker: "VTI", Quantity: 3, Basis: 600, Value: 660, AccountID: "acc_2"},
			{ID: "h_2", Ticker: "VXUS", Quantity: 2, Basis: 100, Value: 120, AccountID: "acc_2"},
		}
		if reverse {
			for i, j := 0, len(accounts)-1; i < j; i, j = i+1, j-1 {
				accounts[i], accounts[j] = accounts[j], accounts[i]
			}
			for i, j := 0, len(transactions)-1; i < j; i, j = i+1, j-1 {
				transactions[i], transactions[j] = transactions[j], transactions[i]
			}
			for i, j := 0, len(holdings)-1; i < j; i, j = i+1, j-1 {
				holdings[i], holdings[j] = holdings[j], holdings[i]
			}
		}
		return &Data{Accounts: accounts, Transactions: transactions, Holdings: holdings, Anchor: d("2026-05-02")}
	}

	first := Generate(newData(false))
	second := Generate(newData(true))
	if first != second {
		t.Fatalf("Generate() not deterministic across input order\n--- first ---\n%s\n--- second ---\n%s", first, second)
	}
	if first == "" {
		t.Fatal("Generate() produced empty output")
	}
	if !strings.Contains(first, "; transfer-partner: tx_d") || !strings.Contains(first, "assets:monarch:savings  $50.00") {
		t.Fatalf("paired transfer resolved incorrectly:\n%s", first)
	}
}
