query Web_GetHoldings($input: PortfolioInput) {
  portfolio(input: $input) {
    aggregateHoldings {
      edges {
        node {
          id
          quantity
          basis
          totalValue
          security {
            id
            name
            ticker
            currentPrice
          }
          holdings {
            id
            quantity
            name
            ticker
            value
            costBasis
            account {
              id
              displayName
            }
          }
        }
      }
    }
  }
}
