package cli

import (
	"bytes"
	"encoding/json"
	"net/http"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
	"time"

	"github.com/thedavidweng/monarchmoney-cli/internal/cache"
	"github.com/thedavidweng/monarchmoney-cli/internal/testutil"
)

func mustCacheDate(t *testing.T, value string) time.Time {
	t.Helper()
	parsed, err := parseCacheDate(value)
	if err != nil {
		t.Fatalf("parseCacheDate(%q) error = %v", value, err)
	}
	return parsed
}

func seedBackupCache(t *testing.T, cachePath string) {
	t.Helper()
	store, err := cache.NewStore(cachePath)
	if err != nil {
		t.Fatalf("NewStore() error = %v", err)
	}
	defer store.Close()

	if err := store.SaveAccounts([]cache.Account{
		{ID: "acc_1", DisplayName: "Checking", TypeGroup: "asset", CurrentBalance: 379.25},
		{ID: "acc_2", DisplayName: "Brokerage", TypeGroup: "investment"},
	}); err != nil {
		t.Fatalf("SaveAccounts() error = %v", err)
	}
	if err := store.SaveTransactions([]cache.Transaction{
		{ID: "tx_1", Date: mustCacheDate(t, "2026-05-09"), Amount: -12.34, Merchant: "Coffee", Category: "Dining", CategoryGroupType: "expense", AccountID: "acc_1"},
	}); err != nil {
		t.Fatalf("SaveTransactions() error = %v", err)
	}
	if err := store.SaveHoldings([]cache.Holding{
		{ID: "h_1", Ticker: "VTI", Quantity: 3.5, Basis: 1000, Value: 1102.5, AccountID: "acc_2"},
	}); err != nil {
		t.Fatalf("SaveHoldings() error = %v", err)
	}
	if err := store.RecordSync(2, 1); err != nil {
		t.Fatalf("RecordSync() error = %v", err)
	}
}

func TestHledgerBackupWritesJournalToDefaultPath(t *testing.T) {
	dir := t.TempDir()
	cachePath := filepath.Join(dir, "cache.sqlite")
	exitCode := withCacheCommandTestDefaults(t, filepath.Join(dir, "session.json"), cachePath)
	seedBackupCache(t, cachePath)
	t.Chdir(dir)

	out := captureStdout(t, func() {
		hledgerBackupCmd.Run(hledgerBackupCmd, nil)
	})

	if *exitCode != 0 {
		t.Fatalf("exitCode = %d; output=%q", *exitCode, out)
	}
	if _, err := os.Stat(filepath.Join(dir, "monarch.journal")); err != nil {
		t.Fatalf("default-path journal not written: %v", err)
	}

	var env struct {
		OK   bool `json:"ok"`
		Data struct {
			Status       string `json:"status"`
			File         string `json:"file"`
			Accounts     int    `json:"accounts"`
			Transactions int    `json:"transactions"`
			Holdings     int    `json:"holdings"`
		} `json:"data"`
		Meta struct {
			Command string `json:"command"`
		} `json:"meta"`
	}
	if err := json.Unmarshal([]byte(out), &env); err != nil {
		t.Fatalf("parse envelope: %v\n%s", err, out)
	}
	if !env.OK || env.Data.Status != "backup complete" || env.Meta.Command != "hledger.backup" {
		t.Fatalf("envelope = %+v", env)
	}
	if env.Data.File != "./monarch.journal" || env.Data.Accounts != 2 || env.Data.Transactions != 1 || env.Data.Holdings != 1 {
		t.Fatalf("envelope data = %+v", env.Data)
	}
}

func TestHledgerBackupJournalContentAndPermissions(t *testing.T) {
	dir := t.TempDir()
	cachePath := filepath.Join(dir, "cache.sqlite")
	exitCode := withCacheCommandTestDefaults(t, filepath.Join(dir, "session.json"), cachePath)
	seedBackupCache(t, cachePath)
	journalPath := filepath.Join(dir, "custom.journal")

	out := captureStdout(t, func() {
		hledgerBackupCmd.Run(hledgerBackupCmd, []string{journalPath})
	})

	if *exitCode != 0 {
		t.Fatalf("exitCode = %d; output=%q", *exitCode, out)
	}

	info, err := os.Stat(journalPath)
	if err != nil {
		t.Fatalf("journal not written: %v", err)
	}
	if runtime.GOOS != "windows" {
		if perm := info.Mode().Perm(); perm != 0o600 {
			t.Fatalf("journal permissions = %o, want 600", perm)
		}
	}

	content, err := os.ReadFile(journalPath)
	if err != nil {
		t.Fatalf("read journal: %v", err)
	}
	journal := string(content)
	for _, want := range []string{
		"; Generated by monarch hledger backup. DO NOT EDIT.",
		"account assets:monarch:checking",
		"; monarch-id: acc_1",
		"2026-05-10 closing balances",
		"$0.00 = $379.25",
		"opening positions investments:monarch:brokerage",
		"3.5 VTI @@ $1000.00",
	} {
		if !strings.Contains(journal, want) {
			t.Fatalf("journal missing %q:\n%s", want, journal)
		}
	}
}

func TestHledgerBackupRegenerationIsByteIdentical(t *testing.T) {
	dir := t.TempDir()
	cachePath := filepath.Join(dir, "cache.sqlite")
	exitCode := withCacheCommandTestDefaults(t, filepath.Join(dir, "session.json"), cachePath)
	seedBackupCache(t, cachePath)
	first := filepath.Join(dir, "first.journal")
	second := filepath.Join(dir, "second.journal")

	captureStdout(t, func() { hledgerBackupCmd.Run(hledgerBackupCmd, []string{first}) })
	captureStdout(t, func() { hledgerBackupCmd.Run(hledgerBackupCmd, []string{second}) })

	if *exitCode != 0 {
		t.Fatalf("exitCode = %d", *exitCode)
	}
	a, err := os.ReadFile(first)
	if err != nil {
		t.Fatal(err)
	}
	b, err := os.ReadFile(second)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(a, b) {
		t.Fatalf("regenerated journal differs:\nfirst:\n%s\nsecond:\n%s", a, b)
	}
}

func TestHledgerBackupOnOutdatedCachePromptsResync(t *testing.T) {
	dir := t.TempDir()
	cachePath := filepath.Join(dir, "cache.sqlite")
	exitCode := withCacheCommandTestDefaults(t, filepath.Join(dir, "session.json"), cachePath)
	createLegacyCacheFile(t, cachePath)

	out := captureStdout(t, func() {
		hledgerBackupCmd.Run(hledgerBackupCmd, []string{filepath.Join(dir, "x.journal")})
	})

	if *exitCode == 0 {
		t.Fatalf("exitCode = 0, want failure on outdated cache; output=%q", out)
	}
	if !strings.Contains(out, "run 'monarch cache sync' to rebuild it") {
		t.Fatalf("output = %q, want re-sync guidance", out)
	}
}

func TestCacheSyncSucceedsWithZeroTransactions(t *testing.T) {
	dir := t.TempDir()
	sessionPath := filepath.Join(dir, "session.json")
	cachePath := filepath.Join(dir, "cache.sqlite")
	exitCode := withCacheCommandTestDefaults(t, sessionPath, cachePath)
	saveTestSession(t, sessionPath)

	http.DefaultTransport = testutil.RoundTripFunc(func(req *http.Request) (*http.Response, error) {
		var gqlReq struct {
			OperationName string `json:"operationName"`
		}
		if err := json.NewDecoder(req.Body).Decode(&gqlReq); err != nil {
			t.Fatalf("Decode request error = %v", err)
		}
		switch gqlReq.OperationName {
		case "GetAccounts":
			return testutil.JSONResponse(`{"data":{"accounts":[{"id":"acc_1","displayName":"Checking","type":{"name":"cash","group":"asset"},"displayBalance":10,"currentBalance":10,"updatedAt":"2026-05-09T10:00:00Z"}]}}`), nil
		case "GetTransactionsList":
			return testutil.JSONResponse(`{"data":{"allTransactions":{"results":[],"totalCount":0}}}`), nil
		case "Web_GetHoldings":
			return testutil.JSONResponse(`{"data":{"portfolio":{"aggregateHoldings":{"edges":[]}}}}`), nil
		default:
			t.Fatalf("unexpected operation %q", gqlReq.OperationName)
		}
		return nil, nil
	})

	out := captureStdout(t, func() {
		cacheSyncCmd.Run(cacheSyncCmd, nil)
	})

	if *exitCode != 0 {
		t.Fatalf("exitCode = %d, want 0 for an account with no transactions; output=%q", *exitCode, out)
	}

	store, err := cache.NewStore(cachePath)
	if err != nil {
		t.Fatalf("NewStore() error = %v", err)
	}
	defer store.Close()
	stats, err := store.GetStats()
	if err != nil {
		t.Fatalf("GetStats() error = %v", err)
	}
	assertStatValue(t, stats, "accounts", 1)
	if _, ok := stats["last_synced_at"]; !ok {
		t.Fatalf("stats = %v, want last_synced_at recorded despite zero transactions", stats)
	}
}

func TestCacheSearchFailsOnUnreadableConfig(t *testing.T) {
	dir := t.TempDir()
	cachePath := filepath.Join(dir, "cache.sqlite")
	exitCode := withCacheCommandTestDefaults(t, filepath.Join(dir, "session.json"), cachePath)
	cfgFile = dir

	out := captureStdout(t, func() {
		cacheSearchCmd.Run(cacheSearchCmd, []string{"coffee"})
	})

	if *exitCode == 0 {
		t.Fatalf("exitCode = 0, want failure when config cannot be loaded; output=%q", out)
	}
	if !strings.Contains(out, "failed to load config") {
		t.Fatalf("output = %q, want config load failure", out)
	}
}

func TestHledgerBackupWriteFailureLeavesNoTempFiles(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("directory permission bits are not enforced on Windows")
	}
	dir := t.TempDir()
	cachePath := filepath.Join(dir, "cache.sqlite")
	exitCode := withCacheCommandTestDefaults(t, filepath.Join(dir, "session.json"), cachePath)
	seedBackupCache(t, cachePath)
	target := filepath.Join(dir, "journal-target")
	if err := os.Mkdir(target, 0o700); err != nil {
		t.Fatal(err)
	}

	out := captureStdout(t, func() {
		hledgerBackupCmd.Run(hledgerBackupCmd, []string{target})
	})

	if *exitCode == 0 {
		t.Fatalf("exitCode = 0, want failure writing onto a directory path; output=%q", out)
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	for _, entry := range entries {
		if strings.HasPrefix(entry.Name(), filepath.Base(target)+".tmp-") {
			t.Fatalf("temporary journal file remains: %s", entry.Name())
		}
	}
}

func TestHledgerBackupHumanOutput(t *testing.T) {
	dir := t.TempDir()
	cachePath := filepath.Join(dir, "cache.sqlite")
	exitCode := withCacheCommandTestDefaults(t, filepath.Join(dir, "session.json"), cachePath)
	seedBackupCache(t, cachePath)
	jsonMode = false
	t.Cleanup(func() { jsonMode = true })
	journalPath := filepath.Join(dir, "human.journal")

	out := captureStdout(t, func() {
		hledgerBackupCmd.Run(hledgerBackupCmd, []string{journalPath})
	})

	if *exitCode != 0 {
		t.Fatalf("exitCode = %d; output=%q", *exitCode, out)
	}
	if !strings.Contains(out, "Wrote "+journalPath+" (2 accounts, 1 transactions, 1 holdings)") {
		t.Fatalf("human output = %q", out)
	}
}

func TestHledgerBackupRenameFailureCleansUp(t *testing.T) {
	dir := t.TempDir()
	cachePath := filepath.Join(dir, "cache.sqlite")
	exitCode := withCacheCommandTestDefaults(t, filepath.Join(dir, "session.json"), cachePath)
	seedBackupCache(t, cachePath)
	target := filepath.Join(dir, "blocked.journal")
	if err := os.Mkdir(target, 0o700); err != nil {
		t.Fatal(err)
	}

	out := captureStdout(t, func() {
		hledgerBackupCmd.Run(hledgerBackupCmd, []string{target})
	})

	if *exitCode == 0 {
		t.Fatalf("exitCode = 0, want failure renaming onto a directory; output=%q", out)
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	for _, e := range entries {
		if strings.Contains(e.Name(), ".tmp-") {
			t.Fatalf("temp file %q left behind after failed rename", e.Name())
		}
	}
}

func TestHledgerBackupAnchorsToLastSyncWithoutTransactions(t *testing.T) {
	dir := t.TempDir()
	cachePath := filepath.Join(dir, "cache.sqlite")
	exitCode := withCacheCommandTestDefaults(t, filepath.Join(dir, "session.json"), cachePath)

	store, err := cache.NewStore(cachePath)
	if err != nil {
		t.Fatalf("NewStore() error = %v", err)
	}
	if err := store.SaveAccounts([]cache.Account{{ID: "acc_1", DisplayName: "Checking", TypeGroup: "asset", CurrentBalance: 25}}); err != nil {
		t.Fatalf("SaveAccounts() error = %v", err)
	}
	if err := store.RecordSync(1, 0); err != nil {
		t.Fatalf("RecordSync() error = %v", err)
	}
	meta, err := store.LastSync()
	if err != nil || meta == nil {
		t.Fatalf("LastSync() = %v, %v", meta, err)
	}
	anchor := meta.SyncedAt.UTC().Format("2006-01-02")
	if err := store.Close(); err != nil {
		t.Fatalf("Close() error = %v", err)
	}
	journalPath := filepath.Join(dir, "anchor.journal")

	out := captureStdout(t, func() {
		hledgerBackupCmd.Run(hledgerBackupCmd, []string{journalPath})
	})

	if *exitCode != 0 {
		t.Fatalf("exitCode = %d; output=%q", *exitCode, out)
	}
	content, err := os.ReadFile(journalPath)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(content), anchor+" closing balances") {
		t.Fatalf("journal not anchored to last sync date %s:\n%s", anchor, content)
	}
}

func TestCacheSyncRegeneratesBackupWhenConfigured(t *testing.T) {
	dir := t.TempDir()
	sessionPath := filepath.Join(dir, "session.json")
	cachePath := filepath.Join(dir, "cache.sqlite")
	backupPath := filepath.Join(dir, "auto.journal")
	exitCode := withCacheCommandTestDefaults(t, sessionPath, cachePath)
	saveTestSession(t, sessionPath)
	t.Setenv("MONARCH_BACKUP_PATH", backupPath)

	http.DefaultTransport = testutil.RoundTripFunc(func(req *http.Request) (*http.Response, error) {
		var gqlReq struct {
			OperationName string `json:"operationName"`
		}
		if err := json.NewDecoder(req.Body).Decode(&gqlReq); err != nil {
			t.Fatalf("Decode request error = %v", err)
		}
		switch gqlReq.OperationName {
		case "GetAccounts":
			return testutil.JSONResponse(`{"data":{"accounts":[{"id":"acc_1","displayName":"Checking","type":{"name":"cash","group":"asset"},"displayBalance":379.25,"currentBalance":379.25,"updatedAt":"2026-05-09T10:00:00Z"}]}}`), nil
		case "GetTransactionsList":
			return testutil.JSONResponse(`{"data":{"allTransactions":{"results":[{"id":"tx_1","date":"2026-05-09","amount":-12.34,"merchant":{"name":"Coffee"},"category":{"name":"Dining","group":{"type":"expense"}},"account":{"id":"acc_1"}}],"totalCount":1}}}`), nil
		case "Web_GetHoldings":
			return testutil.JSONResponse(`{"data":{"portfolio":{"aggregateHoldings":{"edges":[]}}}}`), nil
		default:
			t.Fatalf("unexpected operation %q", gqlReq.OperationName)
		}
		return nil, nil
	})

	out := captureStdout(t, func() {
		cacheSyncCmd.Run(cacheSyncCmd, nil)
	})

	if *exitCode != 0 {
		t.Fatalf("exitCode = %d; output=%q", *exitCode, out)
	}

	content, err := os.ReadFile(backupPath)
	if err != nil {
		t.Fatalf("auto-regenerated journal missing: %v", err)
	}
	journal := string(content)
	if !strings.Contains(journal, "account assets:monarch:checking") || !strings.Contains(journal, "$0.00 = $379.25") {
		t.Fatalf("regenerated journal incomplete:\n%s", journal)
	}

	var env struct {
		Data map[string]any `json:"data"`
	}
	if err := json.Unmarshal([]byte(out), &env); err != nil {
		t.Fatalf("parse envelope: %v\n%s", err, out)
	}
	if env.Data["backup"] != backupPath {
		t.Fatalf("envelope data.backup = %v, want %q", env.Data["backup"], backupPath)
	}
}

func TestCacheSyncBackupFailureSurfacesWarningWithoutFailingSync(t *testing.T) {
	dir := t.TempDir()
	sessionPath := filepath.Join(dir, "session.json")
	cachePath := filepath.Join(dir, "cache.sqlite")
	backupPath := filepath.Join(dir, "absent-dir", "auto.journal")
	exitCode := withCacheCommandTestDefaults(t, sessionPath, cachePath)
	saveTestSession(t, sessionPath)
	t.Setenv("MONARCH_BACKUP_PATH", backupPath)

	http.DefaultTransport = testutil.RoundTripFunc(func(req *http.Request) (*http.Response, error) {
		var gqlReq struct {
			OperationName string `json:"operationName"`
		}
		if err := json.NewDecoder(req.Body).Decode(&gqlReq); err != nil {
			t.Fatalf("Decode request error = %v", err)
		}
		switch gqlReq.OperationName {
		case "GetAccounts":
			return testutil.JSONResponse(`{"data":{"accounts":[{"id":"acc_1","displayName":"Checking","type":{"name":"cash","group":"asset"},"displayBalance":10,"currentBalance":10,"updatedAt":"2026-05-09T10:00:00Z"}]}}`), nil
		case "GetTransactionsList":
			return testutil.JSONResponse(`{"data":{"allTransactions":{"results":[{"id":"tx_1","date":"2026-05-09","amount":-5,"merchant":{"name":"Cafe"},"category":{"name":"Dining"},"account":{"id":"acc_1"}}],"totalCount":1}}}`), nil
		case "Web_GetHoldings":
			return testutil.JSONResponse(`{"data":{"portfolio":{"aggregateHoldings":{"edges":[]}}}}`), nil
		default:
			t.Fatalf("unexpected operation %q", gqlReq.OperationName)
		}
		return nil, nil
	})

	out := captureStdout(t, func() {
		cacheSyncCmd.Run(cacheSyncCmd, nil)
	})

	if *exitCode != 0 {
		t.Fatalf("exitCode = %d, want 0 (regeneration failure must not fail sync); output=%q", *exitCode, out)
	}
	var env struct {
		OK   bool           `json:"ok"`
		Data map[string]any `json:"data"`
		Meta struct {
			Warnings []string `json:"warnings"`
		} `json:"meta"`
	}
	if err := json.Unmarshal([]byte(out), &env); err != nil {
		t.Fatalf("parse envelope: %v\n%s", err, out)
	}
	if !env.OK {
		t.Fatalf("envelope ok = false, want true; output=%q", out)
	}
	if _, ok := env.Data["backup"]; ok {
		t.Fatalf("envelope data.backup = %v, want key absent when regeneration failed", env.Data["backup"])
	}
	if len(env.Meta.Warnings) != 1 || !strings.Contains(env.Meta.Warnings[0], "ledger backup regeneration failed") {
		t.Fatalf("warnings = %v, want ledger backup failure warning", env.Meta.Warnings)
	}
}

func TestCacheSyncSkipsBackupWhenNotConfigured(t *testing.T) {
	dir := t.TempDir()
	sessionPath := filepath.Join(dir, "session.json")
	cachePath := filepath.Join(dir, "cache.sqlite")
	exitCode := withCacheCommandTestDefaults(t, sessionPath, cachePath)
	saveTestSession(t, sessionPath)

	http.DefaultTransport = testutil.RoundTripFunc(func(req *http.Request) (*http.Response, error) {
		var gqlReq struct {
			OperationName string `json:"operationName"`
		}
		if err := json.NewDecoder(req.Body).Decode(&gqlReq); err != nil {
			t.Fatalf("Decode request error = %v", err)
		}
		switch gqlReq.OperationName {
		case "GetAccounts":
			return testutil.JSONResponse(`{"data":{"accounts":[{"id":"acc_1","displayName":"Checking","type":{"name":"cash","group":"asset"},"displayBalance":10,"currentBalance":10,"updatedAt":"2026-05-09T10:00:00Z"}]}}`), nil
		case "GetTransactionsList":
			return testutil.JSONResponse(`{"data":{"allTransactions":{"results":[{"id":"tx_1","date":"2026-05-09","amount":-5,"merchant":{"name":"Cafe"},"category":{"name":"Dining"},"account":{"id":"acc_1"}}],"totalCount":1}}}`), nil
		case "Web_GetHoldings":
			return testutil.JSONResponse(`{"data":{"portfolio":{"aggregateHoldings":{"edges":[]}}}}`), nil
		default:
			t.Fatalf("unexpected operation %q", gqlReq.OperationName)
		}
		return nil, nil
	})

	out := captureStdout(t, func() {
		cacheSyncCmd.Run(cacheSyncCmd, nil)
	})

	if *exitCode != 0 {
		t.Fatalf("exitCode = %d; output=%q", *exitCode, out)
	}
	var env struct {
		Data map[string]any `json:"data"`
	}
	if err := json.Unmarshal([]byte(out), &env); err != nil {
		t.Fatalf("parse envelope: %v\n%s", err, out)
	}
	if _, ok := env.Data["backup"]; ok {
		t.Fatalf("envelope data.backup = %v, want key absent when backup_path unconfigured", env.Data["backup"])
	}
}

func TestHledgerBackupWarnsOnHistoryGaps(t *testing.T) {
	dir := t.TempDir()
	cachePath := filepath.Join(dir, "cache.sqlite")
	exitCode := withCacheCommandTestDefaults(t, filepath.Join(dir, "session.json"), cachePath)
	seedBackupCache(t, cachePath)
	t.Chdir(dir)

	out := captureStdout(t, func() {
		hledgerBackupCmd.Run(hledgerBackupCmd, []string{filepath.Join(dir, "warn.journal")})
	})

	if *exitCode != 0 {
		t.Fatalf("exitCode = %d; output=%q", *exitCode, out)
	}
	if !strings.Contains(out, "monarch cache sync --all' to backfill") || !strings.Contains(out, "\"warnings\":[") {
		t.Fatalf("gap warning missing from envelope: %q", out)
	}
}
