query Common_ListMerchants(
  $search: String
  $limit: Int
  $offset: Int
  $orderBy: MerchantOrdering
  $filters: MerchantFilters
  $includeIds: [ID!]
  $includeMerchantsWithoutTransactions: Boolean
) {
  merchants(
    search: $search
    limit: $limit
    offset: $offset
    orderBy: $orderBy
    filters: $filters
    includeIds: $includeIds
    includeMerchantsWithoutTransactions: $includeMerchantsWithoutTransactions
  ) {
    ...MerchantListFields
  }
}

fragment MerchantListFields on Merchant {
  id
  name
  logoUrl
  transactionCount
  createdAt
  defaultCategory {
    id
    name
  }
  defaultCategoryApplicationMode
  showDefaultCategoryPrompt
  recurringTransactionStream {
    id
  }
}
