query GetTransactionRules {
  transactionRules {
    id
    order
    merchantCriteriaUseOriginalStatement
    merchantCriteria {
      operator
      value
    }
    merchantNameCriteria {
      operator
      value
    }
    originalStatementCriteria {
      operator
      value
    }
    amountCriteria {
      operator
      isExpense
      value
      valueRange {
        lower
        upper
      }
    }
    categoryIds
    categories {
      id
      name
    }
    accountIds
    accounts {
      id
      displayName
    }
    criteriaOwnerIsJoint
    criteriaOwnerUserIds
    criteriaOwnerUsers {
      id
      displayName
    }
    criteriaBusinessEntityIds
    criteriaBusinessEntityIsUnassigned
    criteriaBusinessEntities {
      id
      name
    }
    setCategoryAction {
      id
      name
    }
    setMerchantAction {
      id
      name
    }
    addTagsAction {
      id
      name
      color
    }
    linkGoalAction {
      id
      name
    }
    linkSavingsGoalAction {
      id
      name
    }
    needsReviewByUserAction {
      id
      displayName
    }
    unassignNeedsReviewByUserAction
    sendNotificationAction
    setHideFromReportsAction
    setLinkToPaydownBudgetAction
    reviewStatusAction
    actionSetOwnerIsJoint
    actionSetOwner {
      id
      displayName
    }
    actionSetBusinessEntity {
      id
      name
    }
    actionSetBusinessEntityIsUnassigned
    splitTransactionsAction {
      amountType
      splitsInfo {
        categoryId
        merchantName
        amount
        goalId
        tags
        hideFromReports
        reviewStatus
        needsReviewByUserId
        ownerUserId
        ownerIsJoint
      }
    }
    recentApplicationCount
    lastAppliedAt
  }
}
