mutation Common_UnarchiveSavingsGoal($input: UnarchiveSavingsGoalInput!) {
  unarchiveSavingsGoal(input: $input) {
    savingsGoal {
      ...GoalFields
    }
    errors {
      ...PayloadErrorFields
    }
  }
}

fragment GoalFields on SavingsGoal {
  id
  type
  name
  status
  progress
  currentBalance
  targetDate
  targetAmount
  plannedMonthlyContribution
  currentMonthPlannedContributionAmount
  spendingTotal
  netContribution
  estimatedMonthsUntilCompletion
  forecastedCompletionDate
  isSinkingFund
  priority
}


fragment PayloadErrorFields on PayloadError {
  fieldErrors {
    field
    messages
  }
  message
  code
}
